// Generated by scripts/build-site.mjs — do not edit.
const CACHE='anene-202608020533Z0';
const PRECACHE=["/anene/","/anene/find.html","/anene/about.html","/anene/assets/style.css","/anene/manifest.webmanifest"];
self.addEventListener('install',e=>{
  e.waitUntil(caches.open(CACHE).then(c=>c.addAll(PRECACHE)).then(()=>self.skipWaiting()));
});
self.addEventListener('activate',e=>{
  e.waitUntil(caches.keys().then(ks=>Promise.all(ks.filter(k=>k!==CACHE).map(k=>caches.delete(k)))).then(()=>self.clients.claim()));
});
self.addEventListener('fetch',e=>{
  if(e.request.method!=='GET')return;
  const url=new URL(e.request.url);
  if(url.origin!==location.origin||!url.pathname.startsWith('/anene/'))return;
  e.respondWith(
    caches.match(e.request).then(hit=>{
      const live=fetch(e.request).then(res=>{
        if(res&&res.ok)caches.open(CACHE).then(c=>c.put(e.request,res.clone()));
        return res;
      }).catch(()=>hit);
      return hit||live;
    })
  );
});
